@API_HostAddress = https://localhost:5001/api
@Members = {{API_HostAddress}}/members
@Account = {{API_HostAddress}}/account
@Token = Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5hbmRhbmlAZ21haWwuY29tIiwibmFtZWlkIjoiYTI3ZWRmODAtMDBjMS00MmRiLThjZDQtN2YzMmI0MDhiNTlmIiwiQ3VzdG9tQ2xhaW0iOiJDdXN0b21WYWx1ZSIsIm5iZiI6MTc4MjEyNDkwMiwiZXhwIjoxNzgyNzI5NzAyLCJpYXQiOjE3ODIxMjQ5MDJ9.B1bHUmYAoovlq4I2z_HEN95AugWIbURAv3FwsZSaQ4jE4oxzpHCA9CR5a8ov5M8IuGvwSXWVeO1Y3vRydGX7Jg
@Buggy = {{API_HostAddress}}/buggy

GET {{API_HostAddress}}/weatherforecast/
Accept: application/json

###
GET {{Members}}
Accept: application/json
Authorization: {{Token}}

###
GET {{Members}}/a94782ba-c004-4d65-b552-7eb61ee2a6eb
Accept: application/json
Authorization: {{Token}}

###
POST {{Account}}/register
content-type: application/json

{
    "displayName": "nandani",
    "email": "nandani@gmail.com",
    "password":"afde"
}

###
POST {{Account}}/login
content-type: application/json

{
  "email": "nandani@gmail.com",
  "password":"afde"
}

###
GET {{Buggy}}/server-error
content-type: application/json
